#!/bin/bash

USAGE="html-slides filename.xml"

# Check if arg is null
if [ -n "$1" ]; then

  node ../node_modules/xslt3 -s:$1 -xsl:../html-slides/html-slides-2.xsl -o:index.html

else
  echo Usage: "$USAGE"
fi


